"""
Alert Routes
Read endpoints for Alert management (alerts are GENERATED BY TRIGGERS, not backend)

DBMS Architecture:
- Alerts are created ONLY by MySQL triggers
- Backend reads and marks alerts as resolved
- Triggers automatically insert alerts when conditions are met:
  * Material.quantity < Material.reorder_threshold -> material_low alert
  * Task overdue -> task_delay alert
  * Cost overrun detected -> cost_overrun alert
  * SafetyIncident recorded -> safety_alert alert
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from datetime import datetime

from database import SessionLocal
from models.alert import Alert
from schemas.alert_schema import AlertCreate, AlertResponse

router = APIRouter()


def get_db():
    """Dependency: Get database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@router.get("/", response_model=list[AlertResponse])
def get_all_alerts(
    resolved: bool = False,
    db: Session = Depends(get_db)
):
    """
    GET /alerts
    Retrieve all alerts (active by default)
    
    Query params:
      - resolved: if False (default), return unresolved alerts only
                  if True, return resolved alerts
    
    Returns: List of AlertResponse objects
    
    DBMS Note: Alerts are inserted by triggers when:
    - material_low: Material.quantity <= Material.reorder_threshold
    - cost_overrun: Total costs exceed Budget
    - task_delay: Task.actual_end > Task.planned_end
    - safety_incident: New SafetyIncident recorded
    """
    query = db.query(Alert)
    query = query.filter(Alert.is_resolved == resolved)
    return query.order_by(Alert.created_at.desc()).all()


@router.get("/active", response_model=list[AlertResponse])
def get_active_alerts(db: Session = Depends(get_db)):
    """
    GET /alerts/active
    Retrieve only UNRESOLVED alerts (critical operational view)
    Returns: List of unresolved AlertResponse objects ordered by severity
    
    Priority order: critical -> warning -> info
    """
    alerts = db.query(Alert).filter(Alert.is_resolved == False).all()
    
    # Sort by severity: critical > warning > info
    severity_order = {'critical': 0, 'warning': 1, 'info': 2}
    alerts.sort(key=lambda x: severity_order.get(x.severity, 3))
    
    return alerts


@router.get("/by-area/{area_id}", response_model=list[AlertResponse])
def get_alerts_by_area(
    area_id: int,
    resolved: bool = False,
    severity: str = None,
    db: Session = Depends(get_db)
):
    """
    GET /alerts/by-area/{area_id}
    Retrieve alerts for specific area
    
    Query params:
      - resolved: filter by resolution status (default: False)
      - severity: filter by severity (critical|warning|info)
    
    Returns: List of AlertResponse objects for the area
    DBMS Note: Alerts linked to area via area_id FK
    """
    query = db.query(Alert).filter(Alert.area_id == area_id)
    
    if resolved is not None:
        query = query.filter(Alert.is_resolved == resolved)
    
    if severity:
        query = query.filter(Alert.severity == severity)
    
    return query.order_by(Alert.created_at.desc()).all()


@router.get("/by-severity/{severity}", response_model=list[AlertResponse])
def get_alerts_by_severity(
    severity: str,
    db: Session = Depends(get_db)
):
    """
    GET /alerts/by-severity/{severity}
    Retrieve alerts filtered by severity level
    
    Path param: severity (critical|warning|info)
    Returns: List of unresolved AlertResponse objects with specified severity
    
    Use case: Dashboard displays critical alerts prominently
    """
    if severity not in ['critical', 'warning', 'info']:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Severity must be one of: critical, warning, info"
        )
    
    alerts = db.query(Alert).filter(
        Alert.severity == severity,
        Alert.is_resolved == False
    ).order_by(Alert.created_at.desc()).all()
    
    return alerts


@router.get("/by-type/{alert_type}", response_model=list[AlertResponse])
def get_alerts_by_type(
    alert_type: str,
    db: Session = Depends(get_db)
):
    """
    GET /alerts/by-type/{alert_type}
    Retrieve alerts filtered by alert type
    
    Path param: alert_type (material_low|cost_overrun|task_delay|safety_alert|etc.)
    Returns: List of unresolved AlertResponse objects with specified type
    
    DBMS Note: Alert types are determined by triggers based on business logic:
    - material_low: Inventory falls below reorder threshold
    - cost_overrun: Area costs exceed estimated budget
    - task_delay: Task completion date exceeded
    - safety_alert: Safety incident reported
    - equipment_maintenance: Equipment due for maintenance
    """
    alerts = db.query(Alert).filter(
        Alert.alert_type == alert_type,
        Alert.is_resolved == False
    ).order_by(Alert.created_at.desc()).all()
    
    return alerts


@router.get("/{alert_id}", response_model=AlertResponse)
def get_alert(alert_id: int, db: Session = Depends(get_db)):
    """
    GET /alerts/{alert_id}
    Retrieve alert details by ID
    Returns: AlertResponse object or 404 if not found
    """
    alert = db.query(Alert).filter(Alert.alert_id == alert_id).first()
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with ID {alert_id} not found"
        )
    return alert


@router.put("/{alert_id}/resolve", response_model=AlertResponse)
def resolve_alert(alert_id: int, db: Session = Depends(get_db)):
    """
    PUT /alerts/{alert_id}/resolve
    Mark alert as resolved
    
    Updates: is_resolved = True, resolved_at = NOW()
    
    DBMS Note: This is the ONLY endpoint that writes to Alert table
    (apart from triggers which INSERT)
    
    Use case: User acknowledges and resolves an alert through dashboard
    """
    alert = db.query(Alert).filter(Alert.alert_id == alert_id).first()
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with ID {alert_id} not found"
        )
    
    if alert.is_resolved:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Alert is already resolved"
        )
    
    try:
        alert.is_resolved = True
        alert.resolved_at = datetime.now()
        db.commit()
        db.refresh(alert)
        return alert
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Error resolving alert"
        )


@router.delete("/{alert_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_alert(alert_id: int, db: Session = Depends(get_db)):
    """
    DELETE /alerts/{alert_id}
    Delete alert (typically for resolved/old alerts)
    
    Note: Consider archive instead of delete for audit trail
    """
    alert = db.query(Alert).filter(Alert.alert_id == alert_id).first()
    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with ID {alert_id} not found"
        )
    
    try:
        db.delete(alert)
        db.commit()
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Error deleting alert"
        )


@router.get("/stats/summary", response_model=dict)
def get_alert_statistics(db: Session = Depends(get_db)):
    """
    GET /alerts/stats/summary
    Get alert statistics and dashboard summary
    
    Returns: JSON with alert counts and breakdown
    
    DBMS Query: COUNT(alert_id) grouped by:
    - is_resolved (active vs resolved)
    - severity (critical|warning|info)
    - alert_type
    """
    from sqlalchemy import func
    
    total_alerts = db.query(func.count(Alert.alert_id)).scalar()
    active_alerts = db.query(func.count(Alert.alert_id)).filter(Alert.is_resolved == False).scalar()
    resolved_alerts = db.query(func.count(Alert.alert_id)).filter(Alert.is_resolved == True).scalar()
    
    # Breakdown by severity
    severity_breakdown = db.query(
        Alert.severity,
        func.count(Alert.alert_id).label('count')
    ).filter(Alert.is_resolved == False).group_by(Alert.severity).all()
    
    # Breakdown by type
    type_breakdown = db.query(
        Alert.alert_type,
        func.count(Alert.alert_id).label('count')
    ).filter(Alert.is_resolved == False).group_by(Alert.alert_type).all()
    
    return {
        "total_alerts": total_alerts,
        "active_alerts": active_alerts,
        "resolved_alerts": resolved_alerts,
        "by_severity": [
            {"severity": row[0], "count": row[1]} for row in severity_breakdown
        ],
        "by_type": [
            {"type": row[0], "count": row[1]} for row in type_breakdown
        ]
    }


# ============================================================================
# TRIGGER-TO-BACKEND WORKFLOW DOCUMENTATION
# ============================================================================
"""
HOW TRIGGERS AND BACKEND INTERACT:

1. TRIGGER INSERTION (MySQL Layer)
   └─ Trigger detects condition
      └─ INSERT Alert record into Alert table
         └─ Backend polling or real-time API reads new alert

2. ALERT TYPES AND THEIR TRIGGERS:
   
   a) material_low (Material Inventory)
      Trigger: AFTER UPDATE ON Material
      Condition: NEW.quantity <= NEW.reorder_threshold
      Alert: {"ref_table": "Material", "ref_id": material_id, "type": "material_low"}
      
   b) cost_overrun (Budget Exceeded)
      Trigger: AFTER INSERT ON Cost
      Condition: SUM(Cost.amount) > Budget.estimated_budget
      Alert: {"ref_table": "Cost", "ref_id": cost_id, "type": "cost_overrun"}
      
   c) task_delay (Overdue Tasks)
      Trigger: AFTER UPDATE ON Task
      Condition: CURDATE() > planned_end AND status != 'completed'
      Alert: {"ref_table": "Task", "ref_id": task_id, "type": "task_delay"}
      
   d) safety_incident (Safety Issues)
      Trigger: AFTER INSERT ON SafetyIncident
      Condition: ALWAYS (automatic alert creation)
      Alert: {"ref_table": "SafetyIncident", "ref_id": incident_id, "type": "safety_alert"}

3. BACKEND RESPONSIBILITIES (API Layer)
   ✓ READ: Fetch active/resolved alerts
   ✓ FILTER: By area, severity, type
   ✓ UPDATE: Mark alert as resolved (is_resolved, resolved_at)
   ✓ DELETE: Remove acknowledged/archived alerts
   ✗ CREATE: NEVER insert alerts (triggers only)

4. FRONTEND USAGE
   GET /alerts -> Display active alerts
   GET /alerts/active -> Critical view
   GET /alerts/by-severity/critical -> Red alerts
   PUT /alerts/{id}/resolve -> User acknowledges
   GET /alerts/stats/summary -> Dashboard metrics

5. DATABASE TRIGGERS (SQL - NOT backend code)
   Example trigger:
   
   CREATE TRIGGER alert_material_low
   AFTER UPDATE ON Material
   FOR EACH ROW
   BEGIN
     IF NEW.quantity <= NEW.reorder_threshold THEN
       INSERT INTO Alert (
         area_id, alert_type, ref_table, ref_id, 
         message, severity
       ) VALUES (
         NEW.area_id, 'material_low', 'Material', NEW.material_id,
         CONCAT('Material ', NEW.name, ' below reorder threshold'),
         'warning'
       );
     END IF;
   END;

6. SCALABILITY NOTE
   For high-volume systems, consider:
   - WebSocket connection for real-time alerts
   - Message queue (RabbitMQ) for async processing
   - Alert aggregation to prevent duplicate entries
"""
