/**
 * Engineer Dashboard JavaScript
 * Handles project loading, KPI updates, and user interactions
 * 
 * Features:
 * - Fetch current user information
 * - Load all assigned projects
 * - Display project cards with real-time data
 * - Handle navigation to project details
 */

// API_BASE is already defined in common.js
let allProjects = [];

/**
 * Initialize dashboard on page load
 * - Verify user is authenticated
 * - Load projects
 * - Update KPI cards
 */
async function initializeDashboard() {
    try {
        console.log('=== initializeDashboard START ===');
        
        // Use currentUser from common.js which has already authenticated
        console.log('currentUser:', currentUser);
        
        if (!currentUser) {
            // Not authenticated, redirect to login
            console.log('NOT AUTHENTICATED - Redirecting to login');
            window.location.href = '/login.html';
            return;
        }

        console.log('User is authenticated as:', currentUser.email);

        // Verify engineer role
        console.log('Checking role. Current role:', currentUser.role);
        
        if (currentUser.role !== 'engineer') {
            console.error('Access denied. User role is not engineer');
            alert('Access denied. Engineer role required.');
            window.location.href = '/login.html';
            return;
        }

        console.log('Engineer role verified');

        // Load projects
        console.log('Loading projects...');
        await loadProjects();
        console.log('Projects loaded. Total projects:', allProjects.length);

        // Update KPI cards
        console.log('Updating KPI cards...');
        updateKPICards();

        // Render project cards
        console.log('Rendering project cards...');
        renderProjectCards();

        console.log('=== initializeDashboard COMPLETE ===');

    } catch (error) {
        console.error('=== Dashboard initialization ERROR ===');
        console.error('Error:', error);
        console.error('Error message:', error.message);
        console.error('Error stack:', error.stack);
        alert('Error loading dashboard. Please refresh the page.');
    }
}

/**
 * Load all projects assigned to current engineer
 */
async function loadProjects() {
    try {
        // Use engineer_id if available (for engineers), otherwise fall back to user_id
        const engineerId = currentUser.engineer_id || currentUser.user_id;
        
        const response = await fetch(
            `${API_BASE}/dashboard/engineer/${engineerId}/projects`,
            {
                method: 'GET',
                credentials: 'include'
            }
        );

        if (!response.ok) {
            throw new Error(`Failed to load projects: ${response.statusText}`);
        }

        allProjects = await response.json();
        console.log(`Loaded ${allProjects.length} projects`);
        
    } catch (error) {
        console.error('Error loading projects:', error);
        allProjects = [];
    }
}

/**
 * Update KPI cards with calculated values based on actual project data
 * 
 * DBMS Concept:
 * These metrics are aggregated from the project data using:
 * - Total Projects: COUNT of all areas assigned to engineer
 * - Active Projects: COUNT where status = 'active'
 * - Delayed Tasks: Estimated by comparing task_count vs completed_tasks
 *   - If a project is active but has low completion rate (< 50%), likely has delayed tasks
 * - Open Alerts: SUM of open_alerts across all areas (generated by DB triggers)
 */
function updateKPICards() {
    // 📍 Total Projects
    // Metric: Number of areas/projects assigned to current engineer
    const totalProjectsEl = document.getElementById('totalProjects');
    if (totalProjectsEl) {
        const total = allProjects.length;
        totalProjectsEl.textContent = total;
        console.log(`Total Projects: ${total}`);
    }

    // ✓ Active Projects
    // Metric: Number of projects with status = 'active'
    // DBMS: WHERE status = 'active' in Area table
    const activeProjectsEl = document.getElementById('activeProjects');
    if (activeProjectsEl) {
        const activeCount = allProjects.filter(p => p.status === 'active').length;
        activeProjectsEl.textContent = activeCount;
        console.log(`Active Projects: ${activeCount}`);
    }

    // ⏰ Delayed Tasks
    // Metric: Tasks that are behind schedule
    // Calculation: If project is active AND task completion < 50%, likely has delayed tasks
    // DBMS: Aggregate from Task table with deadline < TODAY and status != 'completed'
    const delayedTasksEl = document.getElementById('delayedTasks');
    if (delayedTasksEl) {
        const delayedCount = allProjects.reduce((sum, project) => {
            if (!project.task_count) return sum;
            
            // Calculate completion percentage for this project
            const completionPercent = project.task_count > 0 
                ? (project.completed_tasks / project.task_count) * 100 
                : 0;
            
            // Consider tasks delayed if:
            // 1. Project is active AND completion is low (< 50%)
            // 2. OR project is on-hold (indicates pause/delay)
            const projectDelayedTasks = project.task_count - project.completed_tasks;
            
            if (project.status === 'active' && completionPercent < 50) {
                return sum + projectDelayedTasks;
            } else if (project.status === 'on-hold') {
                return sum + projectDelayedTasks;
            }
            return sum;
        }, 0);
        delayedTasksEl.textContent = delayedCount;
        console.log(`Delayed Tasks: ${delayedCount}`);
    }

    // 🔔 Open Alerts
    // Metric: Total open alerts across all projects
    // DBMS: Alert table aggregation WHERE status = 'open' AND area_id IN (engineer's areas)
    // Alerts generated by DB triggers for:
    // - Material stock below threshold
    // - Budget overrun
    // - Task delays
    // - Cost overages
    const openAlertsEl = document.getElementById('openAlerts');
    if (openAlertsEl) {
        const totalAlerts = allProjects.reduce((sum, p) => sum + (p.open_alerts || 0), 0);
        openAlertsEl.textContent = totalAlerts;
        console.log(`Open Alerts: ${totalAlerts}`);
    }
}

/**
 * Render project cards in the projects grid
 */
function renderProjectCards() {
    const projectsGrid = document.getElementById('projectsGrid');
    const emptyState = document.getElementById('emptyState');

    // Clear existing cards
    projectsGrid.innerHTML = '';

    if (allProjects.length === 0) {
        // Show empty state
        projectsGrid.style.display = 'none';
        emptyState.style.display = 'block';
        return;
    }

    // Hide empty state
    emptyState.style.display = 'none';
    projectsGrid.style.display = 'grid';

    // Render each project
    allProjects.forEach(project => {
        const card = createProjectCard(project);
        projectsGrid.appendChild(card);
    });
}

/**
 * Create a project card DOM element
 */
function createProjectCard(project) {
    const card = document.createElement('div');
    card.className = 'project-card';

    // Status badge class based on status
    const statusClass = `status-${project.status || 'planned'}`;

    // Color for alerts box
    const alertsClass = project.open_alerts > 0 ? 'critical' : '';

    card.innerHTML = `
        <div class="project-header">
            <div class="project-name">${escapeHtml(project.name)}</div>
            <div class="project-location">📍 ${escapeHtml(project.location || 'Unknown')}</div>
        </div>
        <div class="project-body">
            <!-- Status Badge -->
            <span class="status-badge ${statusClass}">${project.status}</span>

            <!-- Progress Section -->
            <div class="progress-section">
                <div class="progress-label">
                    <span>Task Progress</span>
                    <span>${project.progress_percent}%</span>
                </div>
                <div class="progress-bar">
                    <div class="progress-fill" style="width: ${project.progress_percent}%"></div>
                </div>
            </div>

            <!-- Stats Grid -->
            <div class="stats-grid">
                <div class="stat-item">
                    <div class="stat-value">${project.task_count}</div>
                    <div class="stat-label">Tasks</div>
                </div>
                <div class="stat-item">
                    <div class="stat-value">${project.worker_count}</div>
                    <div class="stat-label">Workers</div>
                </div>
            </div>

            <!-- Alert Box -->
            <div class="alert-box ${alertsClass}">
                <div class="alert-count">
                    ${project.open_alerts} open alert${project.open_alerts !== 1 ? 's' : ''}
                </div>
            </div>

            <!-- Action Button -->
            <button class="btn-view-project" onclick="viewProject(${project.area_id})">
                View Project Details →
            </button>
        </div>
    `;

    return card;
}

/**
 * Navigate to project details page
 */
function viewProject(areaId) {
    console.log('View Project clicked with area_id:', areaId);
    
    if (areaId) {
        const url = `/project_details.html?area_id=${areaId}`;
        console.log('Navigating to:', url);
        window.location.href = url;
    } else {
        console.warn('No area_id provided');
        window.location.href = '/projects.html';
    }
}

/**
 * Utility: Escape HTML to prevent XSS
 */
function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

/**
 * Initialize on DOMContentLoaded
 */
document.addEventListener('DOMContentLoaded', async () => {
    console.log('=== Dashboard Page DOMContentLoaded ===');
    
    // Initialize page header first (from common.js)
    // MUST await this to ensure currentUser is set before initializeDashboard runs
    console.log('Calling initializePageHeader()');
    await initializePageHeader();
    
    // Then initialize dashboard
    console.log('Calling initializeDashboard()');
    await initializeDashboard();
    
    console.log('=== Dashboard Page Initialization Complete ===');
});
