/**
 * Engineer Dashboard JavaScript
 * Handles project loading, KPI updates, and user interactions
 * 
 * Features:
 * - Fetch current user information
 * - Load all assigned projects
 * - Display project cards with real-time data
 * - Handle navigation to project details
 */

const API_BASE = '/api';
let currentUser = null;
let allProjects = [];

/**
 * Initialize dashboard on page load
 * - Verify user is authenticated
 * - Load user info
 * - Load projects
 * - Update KPI cards
 */
async function initializeDashboard() {
    try {
        // Step 1: Get current user
        await loadCurrentUser();
        
        if (!currentUser) {
            // Not authenticated, redirect to login
            window.location.href = '/login.html';
            return;
        }

        // Verify engineer role
        if (currentUser.role !== 'engineer') {
            alert('Access denied. Engineer role required.');
            window.location.href = '/login.html';
            return;
        }

        // Step 2: Update header with engineer name
        updateHeader();

        // Step 3: Load projects
        await loadProjects();

        // Step 4: Update KPI cards
        updateKPICards();

        // Step 5: Render project cards
        renderProjectCards();

    } catch (error) {
        console.error('Dashboard initialization error:', error);
        alert('Error loading dashboard. Please refresh the page.');
    }
}

/**
 * Load current user information from /api/auth/me
 */
async function loadCurrentUser() {
    try {
        const response = await fetch(`${API_BASE}/auth/me`, {
            method: 'GET',
            credentials: 'include'
        });

        if (!response.ok) {
            console.log('User not authenticated');
            return null;
        }

        currentUser = await response.json();
        return currentUser;
    } catch (error) {
        console.error('Error loading current user:', error);
        return null;
    }
}

/**
 * Update header with engineer name
 */
function updateHeader() {
    if (!currentUser) return;
    
    const nameElement = document.getElementById('engineerName');
    if (nameElement) {
        // Extract name from email (everything before @)
        const name = currentUser.email.split('@')[0];
        nameElement.textContent = name.charAt(0).toUpperCase() + name.slice(1);
    }
}

/**
 * Load all projects assigned to current engineer
 */
async function loadProjects() {
    try {
        // Use engineer_id if available (for engineers), otherwise fall back to user_id
        const engineerId = currentUser.engineer_id || currentUser.user_id;
        
        const response = await fetch(
            `${API_BASE}/dashboard/engineer/${engineerId}/projects`,
            {
                method: 'GET',
                credentials: 'include'
            }
        );

        if (!response.ok) {
            throw new Error(`Failed to load projects: ${response.statusText}`);
        }

        allProjects = await response.json();
        console.log(`Loaded ${allProjects.length} projects`);
        
    } catch (error) {
        console.error('Error loading projects:', error);
        allProjects = [];
    }
}

/**
 * Update KPI cards with calculated values based on actual project data
 * 
 * DBMS Concept:
 * These metrics are aggregated from the project data using:
 * - Total Projects: COUNT of all areas assigned to engineer
 * - Active Projects: COUNT where status = 'active'
 * - Delayed Tasks: Estimated by comparing task_count vs completed_tasks
 *   - If a project is active but has low completion rate (< 50%), likely has delayed tasks
 * - Open Alerts: SUM of open_alerts across all areas (generated by DB triggers)
 */
function updateKPICards() {
    // 📍 Total Projects
    // Metric: Number of areas/projects assigned to current engineer
    const totalProjectsEl = document.getElementById('totalProjects');
    if (totalProjectsEl) {
        const total = allProjects.length;
        totalProjectsEl.textContent = total;
        console.log(`Total Projects: ${total}`);
    }

    // ✓ Active Projects
    // Metric: Number of projects with status = 'active'
    // DBMS: WHERE status = 'active' in Area table
    const activeProjectsEl = document.getElementById('activeProjects');
    if (activeProjectsEl) {
        const activeCount = allProjects.filter(p => p.status === 'active').length;
        activeProjectsEl.textContent = activeCount;
        console.log(`Active Projects: ${activeCount}`);
    }

    // ⏰ Delayed Tasks
    // Metric: Tasks that are behind schedule
    // Calculation: If project is active AND task completion < 50%, likely has delayed tasks
    // DBMS: Aggregate from Task table with deadline < TODAY and status != 'completed'
    const delayedTasksEl = document.getElementById('delayedTasks');
    if (delayedTasksEl) {
        const delayedCount = allProjects.reduce((sum, project) => {
            if (!project.task_count) return sum;
            
            // Calculate completion percentage for this project
            const completionPercent = project.task_count > 0 
                ? (project.completed_tasks / project.task_count) * 100 
                : 0;
            
            // Consider tasks delayed if:
            // 1. Project is active AND completion is low (< 50%)
            // 2. OR project is on-hold (indicates pause/delay)
            const projectDelayedTasks = project.task_count - project.completed_tasks;
            
            if (project.status === 'active' && completionPercent < 50) {
                return sum + projectDelayedTasks;
            } else if (project.status === 'on-hold') {
                return sum + projectDelayedTasks;
            }
            return sum;
        }, 0);
        delayedTasksEl.textContent = delayedCount;
        console.log(`Delayed Tasks: ${delayedCount}`);
    }

    // 🔔 Open Alerts
    // Metric: Total open alerts across all projects
    // DBMS: Alert table aggregation WHERE status = 'open' AND area_id IN (engineer's areas)
    // Alerts generated by DB triggers for:
    // - Material stock below threshold
    // - Budget overrun
    // - Task delays
    // - Cost overages
    const openAlertsEl = document.getElementById('openAlerts');
    if (openAlertsEl) {
        const totalAlerts = allProjects.reduce((sum, p) => sum + (p.open_alerts || 0), 0);
        openAlertsEl.textContent = totalAlerts;
        console.log(`Open Alerts: ${totalAlerts}`);
    }
}

/**
 * Render project cards in the projects grid
 */
function renderProjectCards() {
    const projectsGrid = document.getElementById('projectsGrid');
    const emptyState = document.getElementById('emptyState');

    // Clear existing cards
    projectsGrid.innerHTML = '';

    if (allProjects.length === 0) {
        // Show empty state
        projectsGrid.style.display = 'none';
        emptyState.style.display = 'block';
        return;
    }

    // Hide empty state
    emptyState.style.display = 'none';
    projectsGrid.style.display = 'grid';

    // Render each project
    allProjects.forEach(project => {
        const card = createProjectCard(project);
        projectsGrid.appendChild(card);
    });
}

/**
 * Create a project card DOM element
 */
function createProjectCard(project) {
    const card = document.createElement('div');
    card.className = 'project-card';

    // Status badge class based on status
    const statusClass = `status-${project.status || 'planned'}`;

    // Color for alerts box
    const alertsClass = project.open_alerts > 0 ? 'critical' : '';

    card.innerHTML = `
        <div class="project-header">
            <div class="project-name">${escapeHtml(project.name)}</div>
            <div class="project-location">📍 ${escapeHtml(project.location || 'Unknown')}</div>
        </div>
        <div class="project-body">
            <!-- Status Badge -->
            <span class="status-badge ${statusClass}">${project.status}</span>

            <!-- Progress Section -->
            <div class="progress-section">
                <div class="progress-label">
                    <span>Task Progress</span>
                    <span>${project.progress_percent}%</span>
                </div>
                <div class="progress-bar">
                    <div class="progress-fill" style="width: ${project.progress_percent}%"></div>
                </div>
            </div>

            <!-- Stats Grid -->
            <div class="stats-grid">
                <div class="stat-item">
                    <div class="stat-value">${project.task_count}</div>
                    <div class="stat-label">Tasks</div>
                </div>
                <div class="stat-item">
                    <div class="stat-value">${project.worker_count}</div>
                    <div class="stat-label">Workers</div>
                </div>
            </div>

            <!-- Alert Box -->
            <div class="alert-box ${alertsClass}">
                <div class="alert-count">
                    ${project.open_alerts} open alert${project.open_alerts !== 1 ? 's' : ''}
                </div>
            </div>

            <!-- Action Button -->
            <button class="btn-view-project" onclick="viewProject(${project.area_id})">
                View Project Details →
            </button>
        </div>
    `;

    return card;
}

/**
 * Navigate to projects list page
 */
function viewProject(areaId) {
    window.location.href = `/projects.html`;
}

/**
 * Handle logout
 */
async function handleLogout() {
    try {
        const response = await fetch(`${API_BASE}/auth/logout`, {
            method: 'POST',
            credentials: 'include'
        });

        // Redirect to login regardless of response
        window.location.href = '/login.html';
    } catch (error) {
        console.error('Logout error:', error);
        // Still redirect to login
        window.location.href = '/login.html';
    }
}

/**
 * Utility: Escape HTML to prevent XSS
 */
function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

/**
 * Initialize on DOMContentLoaded
 */
document.addEventListener('DOMContentLoaded', () => {
    // Set up logout button
    const logoutBtn = document.getElementById('logoutBtn');
    if (logoutBtn) {
        logoutBtn.addEventListener('click', handleLogout);
    }

    // Initialize dashboard
    initializeDashboard();
});
